name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
        with:
          create_virtualenvs: yes

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Confirm Environment
        run: |
          which poetry
          poetry --version
          which python
          python --version

      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Poetry venv
        uses: actions/cache@v1
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock ') }}

      - name: Create venv
        run: make init

      - name: Lint
        run: make lint-ci

      - name: Test
        run: make tests

      - name: Validate
        run: make check
